spring.application.name=neighbourHood
server.port=${PORT:8080}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.initialization-fail-timeout=10000

# JPA (Java Persistence API for you to access database without real SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Supabase Storage 
supabase.endpoint=${SUPABASE_ENDPOINT}
supabase.access-key=${SUPABASE_ACCESS_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}
supabase.bucket=${SUPABASE_BUCKET}